# Generated by Django 4.2 on 2023-05-14 11:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="rating",
            field=models.IntegerField(default=0),
        ),
    ]
