# Generated by Django 4.2 on 2023-05-14 12:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0002_profile_rating"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="rating",
        ),
    ]
