# Generated by Django 4.2 on 2023-05-01 07:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="cuisine_types",
            field=models.CharField(
                choices=[
                    ("african", "African"),
                    ("american", "American"),
                    ("caribbean", "Caribbean"),
                    ("asian", "Asian"),
                    ("middle_eastern", "Middle Eastern"),
                    ("chinese", "Chinese"),
                    ("indian", "Indian"),
                    ("pakistani", "Pakistani"),
                    ("indonesian", "Indonesian"),
                    ("european", "European"),
                    ("oceanic", "Oceanic"),
                ],
                default="african",
                max_length=50,
            ),
        ),
    ]
