# Generated by Django 4.2 on 2023-05-14 02:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0002_alter_recipe_cuisine_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="rating",
            field=models.IntegerField(default=0),
        ),
    ]
