# Generated by Django 4.1.7 on 2023-06-23 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0006_recipe_cooktime_recipe_preptime_recipe_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="recipe_difficulty",
            field=models.CharField(
                choices=[
                    ("Beginner", "beginner"),
                    ("Intermediate", "intermediate"),
                    ("Advanced", "advanced"),
                    ("Expert", "expert"),
                ],
                default="beginner",
                max_length=50,
            ),
        ),
    ]
