# Generated by Django 4.1.7 on 2023-06-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0007_recipe_recipe_difficulty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="cooktime",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="posted_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="preptime",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="price",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="recipe_difficulty",
            field=models.CharField(
                choices=[
                    ("beginner", "Beginner"),
                    ("intermediate", "Intermediate"),
                    ("advanced", "Advanced"),
                    ("expert", "Expert"),
                ],
                default="beginner",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="servings",
            field=models.IntegerField(),
        ),
    ]
