# Generated by Django 4.1.7 on 2023-06-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0008_alter_recipe_cooktime_alter_recipe_posted_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="cooktime",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="preptime",
        ),
        migrations.AddField(
            model_name="recipe",
            name="cooktime_hours",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="recipe",
            name="cooktime_minutes",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="recipe",
            name="preptime_hours",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="recipe",
            name="preptime_minutes",
            field=models.IntegerField(default=0),
        ),
    ]
