# Generated by Django 4.1.7 on 2023-06-24 11:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0010_recipe_total_preptime"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="total_preptime",
        ),
    ]
