# Generated by Django 4.1.7 on 2023-06-24 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0011_remove_recipe_total_preptime"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="total_preptime",
            field=models.IntegerField(default=0),
        ),
    ]
