# Generated by Django 4.1.7 on 2023-06-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0012_recipe_total_preptime"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="total_cooktime",
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="total_preptime",
            field=models.IntegerField(editable=False),
        ),
    ]
