# Generated by Django 4.1.7 on 2023-06-25 06:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0013_recipe_total_cooktime_alter_recipe_total_preptime"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="rating_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="rating",
            field=models.FloatField(default=0),
        ),
    ]
